import { Injectable, Logger } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import * as nodemailer from 'nodemailer';

@Injectable()
export class MailService {
  private transporter;
  private logger = new Logger(MailService.name);

  constructor(private config: ConfigService) {
    this.transporter = nodemailer.createTransport({
      host: this.config.get('SMTP_HOST'),
      port: Number(this.config.get('SMTP_PORT')),
      secure: this.config.get('SMTP_SECURE') === 'true',
      auth: {
        user: this.config.get('SMTP_USER'),
        pass: this.config.get('SMTP_PASS'),
      },
    });
  }

  async send(to: string, subject: string, html: string) {
    try {
      await this.transporter.sendMail({
        from: this.config.get('SMTP_FROM'),
        to,
        subject,
        html,
      });

      this.logger.log(`Email sent successfully to ${to}`);
    } catch (err) {
      this.logger.error(`Failed to send email to ${to}`, err);
      throw err;
    }
  }

  /**
   * Send a short verification email containing a 6-digit code (no links).
   * tokenPlain is the numeric code generated by the auth logic.
   */
  async sendVerificationEmail(
    to: string,
    _userId: string,
    tokenPlain: string,
    options?: { expiresMinutes?: number },
  ) {
    const expiresMinutes = options?.expiresMinutes ?? 15;

    const subject = 'Your CVX verification code';
    const html = `
      <div style="font-family: Arial, sans-serif; line-height:1.4; color:#111">
        <h2 style="margin-bottom:8px;">Verify your email</h2>
        <p style="margin:0 0 12px 0;">Use the following code to verify your email address:</p>
        <p style="font-size:28px; font-weight:700; letter-spacing:4px; margin:12px 0;">
          ${tokenPlain}
        </p>
        <p style="color:#666;font-size:13px;margin-top:8px;">
          This code expires in ${expiresMinutes} minutes.
        </p>
      </div>
    `;

    await this.send(to, subject, html);
  }
}
